application: prudhvi-movies
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

builtins:
- remote_api: on

handlers:
- url: /static/ext
  static_dir: static/ext
  expiration: "14d 0h"

- url: /static/img
  static_dir: static/img
  expiration: "14d 0h"

- url: /static
  static_dir: static

- url: /admin(/.*)?
  script: main.app
  login: admin
  auth_fail_action: redirect

- url: /task/.*
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
